### ISSUE TITLE
既に入力されている対戦コードに対して情報を登録しようとしてエラーで再入力時に試合詳細入力フォームが増えている

### ISSUE THREAD

**Issue by Matthew238** [kosen-robocon-db/kosen-robocon-db#112]
「作成」ボタンを押下しても登録されることはないので、そのままにしておこうと思いますが、いかがでしょうか？

**Comment by mcre** [comment]
実害がないのであれば後回しで良いと思います

**Comment by Matthew238** [comment]
暫く放置しておきますが、なんとなく原因がわかりました。多分初期化し直せば意図した通りに動くと思います。

**Comment by Matthew238** [comment]
#122でこの問題を解消。

**Comment by Matthew238** [comment]
解消したのでこのissueを閉じます。
