### ISSUE TITLE
seedでdb初期化(全レコードデリート)するようにする

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#15]

**Comment by Matthew238** [comment]
リレーション（has_many/belongs_toなど）を張っているもの同士だと削除の順番を考えないといけないのかな。

**Comment by mcre** [comment]
delete_allだと削除の順番は気にしなくてよさそうです。
(ただし全部まっさらにしてしまわないと不整合が起きそうです)
