### ISSUE TITLE
routesを変更して主キーでURLアクセスできるようにする

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#16]
http://qiita.com/wnoooo/items/d134855f14556b817314

**Comment by Matthew238** [comment]
主キーでアクセス可能にしてきましたが、新しいＭＶＣ作成時に忘れることが予想されるので、閉じずに残しておきましょう。

**Comment by Matthew238** [comment]
closeしても検索できるので、閉じておきます。
