### ISSUE TITLE
seedに全ロボットデータを作成

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#18]
csvとかで持つようにしてもいいかも

**Comment by Matthew238** [comment]
そろそろロボットや試合結果などの登録機能をつけたいと思っているので、新しく得られた情報をダンプしてseedに変換するか、csvファイルにする機能が必要かもしれません。

**Comment by Matthew238** [comment]
CVSファイルがあれば読み込めるようにしたので、これは解決とします。
