### ISSUE TITLE
外部キー制約を付与すべきか

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#20]

**Comment by Matthew238** [comment]
いわゆるマスターテーブル中の大会回数やキャンパスコードなどは削除されることはないだろうと思います。ゆえにそうしたものを外部キーにしてとき、制約がなくても不整合が起きにくいと思います。しかし、テーブル間の関係を明白にするには制約は付与されていたほうがよいと思います。

**Comment by Matthew238** [comment]
#34 で厳格に制約してみましたが、db:seed時やこれから制作する情報入力機能が面倒臭くなったかもしれません。

**Comment by Matthew238** [comment]
外部制約キーを必要とするテーブルが全て実装されたのでこのissueを閉じます。
