### ISSUE TITLE
migarteファイルをきれいにしてもいいのでは

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#21]
現状DB作り直しなので別ファイルでremove_column, add_columnする必要はなくきれいなの作っちゃえば良いはず。

**Comment by Matthew238** [comment]
これはこれから先もありえることなので、ある程度columnの変更を行うmigrationが7-8回に近づいてきたら、習慣的に作り直ししてしまえばよいかもしれませんね。今回、そのあたりはお任せします。

**Comment by mcre** [comment]
ユーザにDBを触らせるシステムだとできないんですけど、いまの状態であればきれいにできるうちにしておいたほうが良いと思うので、適当にやってしまいます。

**Comment by Matthew238** [comment]
migration ファイルを一つにまとめるには Squasher が使えそうです。
[Railsのマイグレーションファイルをまとめる](http://tomy2002.hatenablog.com/entry/2016/02/07/155146)

**Comment by Matthew238** [comment]
定期的、何かの変更毎にInit一つにまとめてしまうことにしませんか？
