### ISSUE TITLE
校名・キャンパス名の変遷を別テーブルで管理

### ISSUE THREAD

**Issue by mcre** [kosen-robocon-db/kosen-robocon-db#26]
#23 参照

**Comment by Matthew238** [comment]
既存のブランチから引き継いでブランチを作ったため、プルリクエスト #34 に含まれてしまいました。機能をまだ追加する予定で、引き続きこの #26 を果たすために実装しますので、#34後にプルリクエストされるまでこのままにしておいてください。

**Comment by Matthew238** [comment]
プルリクエストがマージされたので閉じます。
