### ISSUE TITLE
db:seed時にinsertではなくバルク転送できないか？

### ISSUE THREAD

**Issue by Matthew238** [kosen-robocon-db/kosen-robocon-db#33]
#15 に関連。
大量のシード・データをDBに対してinsertしていると、遅いので、バルク転送できないか？
一気に3000個以上のデータを登録できるのだろうか？
[参考記事1](http://kameryo.hatenablog.com/entry/2015/03/05/201356)
[参考記事2](http://y-yagi.tumblr.com/post/148271974860/activerecord-import%E3%81%AEimport%E3%82%92%E9%80%9F%E3%81%8F%E3%81%99%E3%82%8B)
[参考記事3](http://qiita.com/xend/items/79184ded56158ea1b97a)

**Comment by mcre** [comment]
たしかに時間かかりますね。。
（ローカルだと今のseedで2分位かかりました）
herokuだと早いんですけど。

**Comment by mcre** [comment]
まだ待ちきれないほどではない、ということで保留

**Comment by Matthew238** [comment]
ちょっと改造してバルクインサートを実装し、#49 にてプルリクしました。手許の仮想環境、Herokuのステージングともに成功しました。

**Comment by Matthew238** [comment]
試合関連のテーブルもバルクインサートが必要だと思うので、このissueは残しておきましょう。

**Comment by mcre** [comment]
今ってもう全部バルクインサートですよね？
（であればクローズしたいです

**Comment by Matthew238** [comment]
全てバルクインサートです。よってクローズします。
