### ISSUE TITLE
Heroku上でエラーが見たい

### ISSUE THREAD

**Issue by Matthew238** [kosen-robocon-db/kosen-robocon-db#52]

**Comment by mcre** [comment]
http://qiita.com/llhrkll/items/eb642b0f06b8d7542719
どの権限でlogが見れるかわからないのですが、とりあえずview権限でためしてみましょうか。
herokuのアカウントを教えてください。

**Comment by Matthew238** [comment]
閲覧できるようになりましたので閉じておきます。
